// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: pkg/api/remoteagent/api.proto

package remoteagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionOwner is what owns a session, and so which object the agent
// authorizes a request against and builds it from: the ResourceClaim the
// devices were allocated to (DRA path), or the Pod a device plugin allocated
// them for (device-plugin path). The claim_* fields carry that object's
// identity either way.
type SessionOwner int32

const (
	// A request that names no owner comes from a DRA-path caller that predates
	// pod-owned sessions, so claim is the zero value.
	SessionOwner_SESSION_OWNER_CLAIM SessionOwner = 0
	SessionOwner_SESSION_OWNER_POD   SessionOwner = 1
)

// Enum value maps for SessionOwner.
var (
	SessionOwner_name = map[int32]string{
		0: "SESSION_OWNER_CLAIM",
		1: "SESSION_OWNER_POD",
	}
	SessionOwner_value = map[string]int32{
		"SESSION_OWNER_CLAIM": 0,
		"SESSION_OWNER_POD":   1,
	}
)

func (x SessionOwner) Enum() *SessionOwner {
	p := new(SessionOwner)
	*p = x
	return p
}

func (x SessionOwner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionOwner) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_remoteagent_api_proto_enumTypes[0].Descriptor()
}

func (SessionOwner) Type() protoreflect.EnumType {
	return &file_pkg_api_remoteagent_api_proto_enumTypes[0]
}

func (x SessionOwner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionOwner.Descriptor instead.
func (SessionOwner) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{0}
}

type EnsureSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session token: the value the consumer pod receives as LUPINE_SESSION and
	// the name of the session directory on this node.
	Session        string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ClaimUid       string `protobuf:"bytes,2,opt,name=claim_uid,json=claimUid,proto3" json:"claim_uid,omitempty"`
	ClaimNamespace string `protobuf:"bytes,3,opt,name=claim_namespace,json=claimNamespace,proto3" json:"claim_namespace,omitempty"`
	ClaimName      string `protobuf:"bytes,4,opt,name=claim_name,json=claimName,proto3" json:"claim_name,omitempty"`
	// Requests names the claim requests (main request names) that belong to
	// this session; the agent materializes only their devices. Empty means
	// every request of the claim (legacy 1:1 form).
	Requests []string `protobuf:"bytes,5,rep,name=requests,proto3" json:"requests,omitempty"`
	// Partition is the resolver's partition key (informational, logged and
	// recorded in the session marker).
	Partition string `protobuf:"bytes,6,opt,name=partition,proto3" json:"partition,omitempty"`
	// claim_resource_version is the claim version the caller decided the
	// session against (it recorded the token on that version). An agent whose
	// cached claim is older than this reads the claim from the API instead of
	// failing on a stale cache.
	ClaimResourceVersion string `protobuf:"bytes,7,opt,name=claim_resource_version,json=claimResourceVersion,proto3" json:"claim_resource_version,omitempty"`
	// owner routes the request: the claim_* fields name a claim, or a pod.
	Owner         SessionOwner `protobuf:"varint,8,opt,name=owner,proto3,enum=remoteagent.SessionOwner" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureSessionRequest) Reset() {
	*x = EnsureSessionRequest{}
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureSessionRequest) ProtoMessage() {}

func (x *EnsureSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureSessionRequest.ProtoReflect.Descriptor instead.
func (*EnsureSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureSessionRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *EnsureSessionRequest) GetClaimUid() string {
	if x != nil {
		return x.ClaimUid
	}
	return ""
}

func (x *EnsureSessionRequest) GetClaimNamespace() string {
	if x != nil {
		return x.ClaimNamespace
	}
	return ""
}

func (x *EnsureSessionRequest) GetClaimName() string {
	if x != nil {
		return x.ClaimName
	}
	return ""
}

func (x *EnsureSessionRequest) GetRequests() []string {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *EnsureSessionRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *EnsureSessionRequest) GetClaimResourceVersion() string {
	if x != nil {
		return x.ClaimResourceVersion
	}
	return ""
}

func (x *EnsureSessionRequest) GetOwner() SessionOwner {
	if x != nil {
		return x.Owner
	}
	return SessionOwner_SESSION_OWNER_CLAIM
}

type EnsureSessionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ready             bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	CudaDriverVersion string                 `protobuf:"bytes,2,opt,name=cuda_driver_version,json=cudaDriverVersion,proto3" json:"cuda_driver_version,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// server_endpoint is the lupine-server address clients must be given
	// (URL form), as the agent currently knows it. Empty when the agent has
	// no routable address for its server yet.
	ServerEndpoint string `protobuf:"bytes,4,opt,name=server_endpoint,json=serverEndpoint,proto3" json:"server_endpoint,omitempty"`
	// client_bundle_etag is the etag of the client bundle lupine-server embeds
	// for this node's platform (the build identity clients must match; see
	// FetchClientBundle). Empty when the server exposes no bundle or the agent
	// has not read it yet.
	ClientBundleEtag string `protobuf:"bytes,5,opt,name=client_bundle_etag,json=clientBundleEtag,proto3" json:"client_bundle_etag,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnsureSessionResponse) Reset() {
	*x = EnsureSessionResponse{}
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureSessionResponse) ProtoMessage() {}

func (x *EnsureSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureSessionResponse.ProtoReflect.Descriptor instead.
func (*EnsureSessionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureSessionResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *EnsureSessionResponse) GetCudaDriverVersion() string {
	if x != nil {
		return x.CudaDriverVersion
	}
	return ""
}

func (x *EnsureSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnsureSessionResponse) GetServerEndpoint() string {
	if x != nil {
		return x.ServerEndpoint
	}
	return ""
}

func (x *EnsureSessionResponse) GetClientBundleEtag() string {
	if x != nil {
		return x.ClientBundleEtag
	}
	return ""
}

type ReleaseSessionsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClaimUid string                 `protobuf:"bytes,1,opt,name=claim_uid,json=claimUid,proto3" json:"claim_uid,omitempty"`
	// tokens of the sessions to remove; at least one. Tokens that do not
	// belong to the claim are ignored.
	Tokens []string `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	// owner routes the request: claim_uid is a claim UID, or a pod UID.
	Owner         SessionOwner `protobuf:"varint,3,opt,name=owner,proto3,enum=remoteagent.SessionOwner" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionsRequest) Reset() {
	*x = ReleaseSessionsRequest{}
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionsRequest) ProtoMessage() {}

func (x *ReleaseSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSessionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseSessionsRequest) GetClaimUid() string {
	if x != nil {
		return x.ClaimUid
	}
	return ""
}

func (x *ReleaseSessionsRequest) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ReleaseSessionsRequest) GetOwner() SessionOwner {
	if x != nil {
		return x.Owner
	}
	return SessionOwner_SESSION_OWNER_CLAIM
}

type ReleaseSessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// released is how many sessions were removed by this call.
	Released      int32 `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionsResponse) Reset() {
	*x = ReleaseSessionsResponse{}
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionsResponse) ProtoMessage() {}

func (x *ReleaseSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSessionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseSessionsResponse) GetReleased() int32 {
	if x != nil {
		return x.Released
	}
	return 0
}

type ServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoRequest) Reset() {
	*x = ServerInfoRequest{}
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoRequest) ProtoMessage() {}

func (x *ServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{4}
}

type ServerInfoResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Listening bool                   `protobuf:"varint,1,opt,name=listening,proto3" json:"listening,omitempty"`
	// endpoint is the lupine-server address other nodes should use (URL
	// form): advertised by the operator, or discovered by the agent. Empty
	// while unknown.
	Endpoint          string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CudaDriverVersion string `protobuf:"bytes,3,opt,name=cuda_driver_version,json=cudaDriverVersion,proto3" json:"cuda_driver_version,omitempty"`
	NodeName          string `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// agent_endpoint is this agent's own address other nodes should use for
	// EnsureSession (grpc://host:port). Empty while unknown, or when the
	// agent listens on a unix socket only.
	AgentEndpoint string `protobuf:"bytes,5,opt,name=agent_endpoint,json=agentEndpoint,proto3" json:"agent_endpoint,omitempty"`
	// client_bundle_etag: see EnsureSessionResponse.
	ClientBundleEtag string `protobuf:"bytes,6,opt,name=client_bundle_etag,json=clientBundleEtag,proto3" json:"client_bundle_etag,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{5}
}

func (x *ServerInfoResponse) GetListening() bool {
	if x != nil {
		return x.Listening
	}
	return false
}

func (x *ServerInfoResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ServerInfoResponse) GetCudaDriverVersion() string {
	if x != nil {
		return x.CudaDriverVersion
	}
	return ""
}

func (x *ServerInfoResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ServerInfoResponse) GetAgentEndpoint() string {
	if x != nil {
		return x.AgentEndpoint
	}
	return ""
}

func (x *ServerInfoResponse) GetClientBundleEtag() string {
	if x != nil {
		return x.ClientBundleEtag
	}
	return ""
}

type FetchClientBundleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authorization: a session token of the owner named below (as EnsureSession).
	Session        string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ClaimUid       string `protobuf:"bytes,2,opt,name=claim_uid,json=claimUid,proto3" json:"claim_uid,omitempty"`
	ClaimNamespace string `protobuf:"bytes,3,opt,name=claim_namespace,json=claimNamespace,proto3" json:"claim_namespace,omitempty"`
	ClaimName      string `protobuf:"bytes,4,opt,name=claim_name,json=claimName,proto3" json:"claim_name,omitempty"`
	// Platform of the bundle: os "linux" (default) and arch "amd64"/"arm64"
	// (default: the agent's own, i.e. the GPU node's).
	Os   string `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Arch string `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	// if_none_match: an etag the caller already has; when it is current the
	// stream carries metadata only.
	IfNoneMatch string `protobuf:"bytes,7,opt,name=if_none_match,json=ifNoneMatch,proto3" json:"if_none_match,omitempty"`
	// owner routes the authorization: the token is recorded on a claim, or
	// derived from a pod. See EnsureSessionRequest.owner.
	Owner         SessionOwner `protobuf:"varint,8,opt,name=owner,proto3,enum=remoteagent.SessionOwner" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchClientBundleRequest) Reset() {
	*x = FetchClientBundleRequest{}
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchClientBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchClientBundleRequest) ProtoMessage() {}

func (x *FetchClientBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchClientBundleRequest.ProtoReflect.Descriptor instead.
func (*FetchClientBundleRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{6}
}

func (x *FetchClientBundleRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *FetchClientBundleRequest) GetClaimUid() string {
	if x != nil {
		return x.ClaimUid
	}
	return ""
}

func (x *FetchClientBundleRequest) GetClaimNamespace() string {
	if x != nil {
		return x.ClaimNamespace
	}
	return ""
}

func (x *FetchClientBundleRequest) GetClaimName() string {
	if x != nil {
		return x.ClaimName
	}
	return ""
}

func (x *FetchClientBundleRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *FetchClientBundleRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *FetchClientBundleRequest) GetIfNoneMatch() string {
	if x != nil {
		return x.IfNoneMatch
	}
	return ""
}

func (x *FetchClientBundleRequest) GetOwner() SessionOwner {
	if x != nil {
		return x.Owner
	}
	return SessionOwner_SESSION_OWNER_CLAIM
}

type ClientBundleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	ContentDigest string                 `protobuf:"bytes,2,opt,name=content_digest,json=contentDigest,proto3" json:"content_digest,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	NotModified   bool                   `protobuf:"varint,6,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientBundleInfo) Reset() {
	*x = ClientBundleInfo{}
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientBundleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBundleInfo) ProtoMessage() {}

func (x *ClientBundleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBundleInfo.ProtoReflect.Descriptor instead.
func (*ClientBundleInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{7}
}

func (x *ClientBundleInfo) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ClientBundleInfo) GetContentDigest() string {
	if x != nil {
		return x.ContentDigest
	}
	return ""
}

func (x *ClientBundleInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ClientBundleInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ClientBundleInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ClientBundleInfo) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

type FetchClientBundleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*FetchClientBundleResponse_Info
	//	*FetchClientBundleResponse_Chunk
	Body          isFetchClientBundleResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchClientBundleResponse) Reset() {
	*x = FetchClientBundleResponse{}
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchClientBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchClientBundleResponse) ProtoMessage() {}

func (x *FetchClientBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchClientBundleResponse.ProtoReflect.Descriptor instead.
func (*FetchClientBundleResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{8}
}

func (x *FetchClientBundleResponse) GetBody() isFetchClientBundleResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *FetchClientBundleResponse) GetInfo() *ClientBundleInfo {
	if x != nil {
		if x, ok := x.Body.(*FetchClientBundleResponse_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *FetchClientBundleResponse) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Body.(*FetchClientBundleResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isFetchClientBundleResponse_Body interface {
	isFetchClientBundleResponse_Body()
}

type FetchClientBundleResponse_Info struct {
	Info *ClientBundleInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type FetchClientBundleResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*FetchClientBundleResponse_Info) isFetchClientBundleResponse_Body() {}

func (*FetchClientBundleResponse_Chunk) isFetchClientBundleResponse_Body() {}

var File_pkg_api_remoteagent_api_proto protoreflect.FileDescriptor

const file_pkg_api_remoteagent_api_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/api/remoteagent/api.proto\x12\vremoteagent\"\xb6\x02\n" +
	"\x14EnsureSessionRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x1b\n" +
	"\tclaim_uid\x18\x02 \x01(\tR\bclaimUid\x12'\n" +
	"\x0fclaim_namespace\x18\x03 \x01(\tR\x0eclaimNamespace\x12\x1d\n" +
	"\n" +
	"claim_name\x18\x04 \x01(\tR\tclaimName\x12\x1a\n" +
	"\brequests\x18\x05 \x03(\tR\brequests\x12\x1c\n" +
	"\tpartition\x18\x06 \x01(\tR\tpartition\x124\n" +
	"\x16claim_resource_version\x18\a \x01(\tR\x14claimResourceVersion\x12/\n" +
	"\x05owner\x18\b \x01(\x0e2\x19.remoteagent.SessionOwnerR\x05owner\"\xce\x01\n" +
	"\x15EnsureSessionResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12.\n" +
	"\x13cuda_driver_version\x18\x02 \x01(\tR\x11cudaDriverVersion\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12'\n" +
	"\x0fserver_endpoint\x18\x04 \x01(\tR\x0eserverEndpoint\x12,\n" +
	"\x12client_bundle_etag\x18\x05 \x01(\tR\x10clientBundleEtag\"~\n" +
	"\x16ReleaseSessionsRequest\x12\x1b\n" +
	"\tclaim_uid\x18\x01 \x01(\tR\bclaimUid\x12\x16\n" +
	"\x06tokens\x18\x02 \x03(\tR\x06tokens\x12/\n" +
	"\x05owner\x18\x03 \x01(\x0e2\x19.remoteagent.SessionOwnerR\x05owner\"5\n" +
	"\x17ReleaseSessionsResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\x05R\breleased\"\x13\n" +
	"\x11ServerInfoRequest\"\xf0\x01\n" +
	"\x12ServerInfoResponse\x12\x1c\n" +
	"\tlistening\x18\x01 \x01(\bR\tlistening\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12.\n" +
	"\x13cuda_driver_version\x18\x03 \x01(\tR\x11cudaDriverVersion\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12%\n" +
	"\x0eagent_endpoint\x18\x05 \x01(\tR\ragentEndpoint\x12,\n" +
	"\x12client_bundle_etag\x18\x06 \x01(\tR\x10clientBundleEtag\"\x92\x02\n" +
	"\x18FetchClientBundleRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x1b\n" +
	"\tclaim_uid\x18\x02 \x01(\tR\bclaimUid\x12'\n" +
	"\x0fclaim_namespace\x18\x03 \x01(\tR\x0eclaimNamespace\x12\x1d\n" +
	"\n" +
	"claim_name\x18\x04 \x01(\tR\tclaimName\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12\"\n" +
	"\rif_none_match\x18\a \x01(\tR\vifNoneMatch\x12/\n" +
	"\x05owner\x18\b \x01(\x0e2\x19.remoteagent.SessionOwnerR\x05owner\"\xc3\x01\n" +
	"\x10ClientBundleInfo\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12%\n" +
	"\x0econtent_digest\x18\x02 \x01(\tR\rcontentDigest\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12!\n" +
	"\fnot_modified\x18\x06 \x01(\bR\vnotModified\"p\n" +
	"\x19FetchClientBundleResponse\x123\n" +
	"\x04info\x18\x01 \x01(\v2\x1d.remoteagent.ClientBundleInfoH\x00R\x04info\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04body*>\n" +
	"\fSessionOwner\x12\x17\n" +
	"\x13SESSION_OWNER_CLAIM\x10\x00\x12\x15\n" +
	"\x11SESSION_OWNER_POD\x10\x012\x80\x03\n" +
	"\vRemoteAgent\x12X\n" +
	"\rEnsureSession\x12!.remoteagent.EnsureSessionRequest\x1a\".remoteagent.EnsureSessionResponse\"\x00\x12O\n" +
	"\n" +
	"ServerInfo\x12\x1e.remoteagent.ServerInfoRequest\x1a\x1f.remoteagent.ServerInfoResponse\"\x00\x12^\n" +
	"\x0fReleaseSessions\x12#.remoteagent.ReleaseSessionsRequest\x1a$.remoteagent.ReleaseSessionsResponse\"\x00\x12f\n" +
	"\x11FetchClientBundle\x12%.remoteagent.FetchClientBundleRequest\x1a&.remoteagent.FetchClientBundleResponse\"\x000\x01B\x15Z\x13pkg/api/remoteagentb\x06proto3"

var (
	file_pkg_api_remoteagent_api_proto_rawDescOnce sync.Once
	file_pkg_api_remoteagent_api_proto_rawDescData []byte
)

func file_pkg_api_remoteagent_api_proto_rawDescGZIP() []byte {
	file_pkg_api_remoteagent_api_proto_rawDescOnce.Do(func() {
		file_pkg_api_remoteagent_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_remoteagent_api_proto_rawDesc), len(file_pkg_api_remoteagent_api_proto_rawDesc)))
	})
	return file_pkg_api_remoteagent_api_proto_rawDescData
}

var file_pkg_api_remoteagent_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_remoteagent_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_api_remoteagent_api_proto_goTypes = []any{
	(SessionOwner)(0),                 // 0: remoteagent.SessionOwner
	(*EnsureSessionRequest)(nil),      // 1: remoteagent.EnsureSessionRequest
	(*EnsureSessionResponse)(nil),     // 2: remoteagent.EnsureSessionResponse
	(*ReleaseSessionsRequest)(nil),    // 3: remoteagent.ReleaseSessionsRequest
	(*ReleaseSessionsResponse)(nil),   // 4: remoteagent.ReleaseSessionsResponse
	(*ServerInfoRequest)(nil),         // 5: remoteagent.ServerInfoRequest
	(*ServerInfoResponse)(nil),        // 6: remoteagent.ServerInfoResponse
	(*FetchClientBundleRequest)(nil),  // 7: remoteagent.FetchClientBundleRequest
	(*ClientBundleInfo)(nil),          // 8: remoteagent.ClientBundleInfo
	(*FetchClientBundleResponse)(nil), // 9: remoteagent.FetchClientBundleResponse
}
var file_pkg_api_remoteagent_api_proto_depIdxs = []int32{
	0, // 0: remoteagent.EnsureSessionRequest.owner:type_name -> remoteagent.SessionOwner
	0, // 1: remoteagent.ReleaseSessionsRequest.owner:type_name -> remoteagent.SessionOwner
	0, // 2: remoteagent.FetchClientBundleRequest.owner:type_name -> remoteagent.SessionOwner
	8, // 3: remoteagent.FetchClientBundleResponse.info:type_name -> remoteagent.ClientBundleInfo
	1, // 4: remoteagent.RemoteAgent.EnsureSession:input_type -> remoteagent.EnsureSessionRequest
	5, // 5: remoteagent.RemoteAgent.ServerInfo:input_type -> remoteagent.ServerInfoRequest
	3, // 6: remoteagent.RemoteAgent.ReleaseSessions:input_type -> remoteagent.ReleaseSessionsRequest
	7, // 7: remoteagent.RemoteAgent.FetchClientBundle:input_type -> remoteagent.FetchClientBundleRequest
	2, // 8: remoteagent.RemoteAgent.EnsureSession:output_type -> remoteagent.EnsureSessionResponse
	6, // 9: remoteagent.RemoteAgent.ServerInfo:output_type -> remoteagent.ServerInfoResponse
	4, // 10: remoteagent.RemoteAgent.ReleaseSessions:output_type -> remoteagent.ReleaseSessionsResponse
	9, // 11: remoteagent.RemoteAgent.FetchClientBundle:output_type -> remoteagent.FetchClientBundleResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_api_remoteagent_api_proto_init() }
func file_pkg_api_remoteagent_api_proto_init() {
	if File_pkg_api_remoteagent_api_proto != nil {
		return
	}
	file_pkg_api_remoteagent_api_proto_msgTypes[8].OneofWrappers = []any{
		(*FetchClientBundleResponse_Info)(nil),
		(*FetchClientBundleResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_remoteagent_api_proto_rawDesc), len(file_pkg_api_remoteagent_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_remoteagent_api_proto_goTypes,
		DependencyIndexes: file_pkg_api_remoteagent_api_proto_depIdxs,
		EnumInfos:         file_pkg_api_remoteagent_api_proto_enumTypes,
		MessageInfos:      file_pkg_api_remoteagent_api_proto_msgTypes,
	}.Build()
	File_pkg_api_remoteagent_api_proto = out.File
	file_pkg_api_remoteagent_api_proto_goTypes = nil
	file_pkg_api_remoteagent_api_proto_depIdxs = nil
}
