// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v5.29.3
// source: api.proto

package remoteagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsureSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session token: the value the consumer pod receives as LUPINE_SESSION and
	// the name of the session directory on this node.
	Session        string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ClaimUid       string `protobuf:"bytes,2,opt,name=claim_uid,json=claimUid,proto3" json:"claim_uid,omitempty"`
	ClaimNamespace string `protobuf:"bytes,3,opt,name=claim_namespace,json=claimNamespace,proto3" json:"claim_namespace,omitempty"`
	ClaimName      string `protobuf:"bytes,4,opt,name=claim_name,json=claimName,proto3" json:"claim_name,omitempty"`
	// Requests names the claim requests (main request names) that belong to
	// this session; the agent materializes only their devices. Empty means
	// every request of the claim (legacy 1:1 form).
	Requests []string `protobuf:"bytes,5,rep,name=requests,proto3" json:"requests,omitempty"`
	// Partition is the resolver's partition key (informational, logged and
	// recorded in the session marker).
	Partition     string `protobuf:"bytes,6,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureSessionRequest) Reset() {
	*x = EnsureSessionRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureSessionRequest) ProtoMessage() {}

func (x *EnsureSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureSessionRequest.ProtoReflect.Descriptor instead.
func (*EnsureSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureSessionRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *EnsureSessionRequest) GetClaimUid() string {
	if x != nil {
		return x.ClaimUid
	}
	return ""
}

func (x *EnsureSessionRequest) GetClaimNamespace() string {
	if x != nil {
		return x.ClaimNamespace
	}
	return ""
}

func (x *EnsureSessionRequest) GetClaimName() string {
	if x != nil {
		return x.ClaimName
	}
	return ""
}

func (x *EnsureSessionRequest) GetRequests() []string {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *EnsureSessionRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

type EnsureSessionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ready             bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	CudaDriverVersion string                 `protobuf:"bytes,2,opt,name=cuda_driver_version,json=cudaDriverVersion,proto3" json:"cuda_driver_version,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnsureSessionResponse) Reset() {
	*x = EnsureSessionResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureSessionResponse) ProtoMessage() {}

func (x *EnsureSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureSessionResponse.ProtoReflect.Descriptor instead.
func (*EnsureSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureSessionResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *EnsureSessionResponse) GetCudaDriverVersion() string {
	if x != nil {
		return x.CudaDriverVersion
	}
	return ""
}

func (x *EnsureSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoRequest) Reset() {
	*x = ServerInfoRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoRequest) ProtoMessage() {}

func (x *ServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

type ServerInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Listening         bool                   `protobuf:"varint,1,opt,name=listening,proto3" json:"listening,omitempty"`
	Endpoint          string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CudaDriverVersion string                 `protobuf:"bytes,3,opt,name=cuda_driver_version,json=cudaDriverVersion,proto3" json:"cuda_driver_version,omitempty"`
	NodeName          string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *ServerInfoResponse) GetListening() bool {
	if x != nil {
		return x.Listening
	}
	return false
}

func (x *ServerInfoResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ServerInfoResponse) GetCudaDriverVersion() string {
	if x != nil {
		return x.CudaDriverVersion
	}
	return ""
}

func (x *ServerInfoResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\vremoteagent\"\xcf\x01\n" +
	"\x14EnsureSessionRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x1b\n" +
	"\tclaim_uid\x18\x02 \x01(\tR\bclaimUid\x12'\n" +
	"\x0fclaim_namespace\x18\x03 \x01(\tR\x0eclaimNamespace\x12\x1d\n" +
	"\n" +
	"claim_name\x18\x04 \x01(\tR\tclaimName\x12\x1a\n" +
	"\brequests\x18\x05 \x03(\tR\brequests\x12\x1c\n" +
	"\tpartition\x18\x06 \x01(\tR\tpartition\"w\n" +
	"\x15EnsureSessionResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12.\n" +
	"\x13cuda_driver_version\x18\x02 \x01(\tR\x11cudaDriverVersion\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x13\n" +
	"\x11ServerInfoRequest\"\x9b\x01\n" +
	"\x12ServerInfoResponse\x12\x1c\n" +
	"\tlistening\x18\x01 \x01(\bR\tlistening\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12.\n" +
	"\x13cuda_driver_version\x18\x03 \x01(\tR\x11cudaDriverVersion\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName2\xb8\x01\n" +
	"\vRemoteAgent\x12X\n" +
	"\rEnsureSession\x12!.remoteagent.EnsureSessionRequest\x1a\".remoteagent.EnsureSessionResponse\"\x00\x12O\n" +
	"\n" +
	"ServerInfo\x12\x1e.remoteagent.ServerInfoRequest\x1a\x1f.remoteagent.ServerInfoResponse\"\x00B\x15Z\x13pkg/api/remoteagentb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_goTypes = []any{
	(*EnsureSessionRequest)(nil),  // 0: remoteagent.EnsureSessionRequest
	(*EnsureSessionResponse)(nil), // 1: remoteagent.EnsureSessionResponse
	(*ServerInfoRequest)(nil),     // 2: remoteagent.ServerInfoRequest
	(*ServerInfoResponse)(nil),    // 3: remoteagent.ServerInfoResponse
}
var file_api_proto_depIdxs = []int32{
	0, // 0: remoteagent.RemoteAgent.EnsureSession:input_type -> remoteagent.EnsureSessionRequest
	2, // 1: remoteagent.RemoteAgent.ServerInfo:input_type -> remoteagent.ServerInfoRequest
	1, // 2: remoteagent.RemoteAgent.EnsureSession:output_type -> remoteagent.EnsureSessionResponse
	3, // 3: remoteagent.RemoteAgent.ServerInfo:output_type -> remoteagent.ServerInfoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
