// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.1
// source: pkg/api/remoteagent/api.proto

package remoteagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsureSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Session token: the value the consumer pod receives as LUPINE_SESSION and
	// the name of the session directory on this node.
	Session        string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ClaimUid       string `protobuf:"bytes,2,opt,name=claim_uid,json=claimUid,proto3" json:"claim_uid,omitempty"`
	ClaimNamespace string `protobuf:"bytes,3,opt,name=claim_namespace,json=claimNamespace,proto3" json:"claim_namespace,omitempty"`
	ClaimName      string `protobuf:"bytes,4,opt,name=claim_name,json=claimName,proto3" json:"claim_name,omitempty"`
	// Requests names the claim requests (main request names) that belong to
	// this session; the agent materializes only their devices. Empty means
	// every request of the claim (legacy 1:1 form).
	Requests []string `protobuf:"bytes,5,rep,name=requests,proto3" json:"requests,omitempty"`
	// Partition is the resolver's partition key (informational, logged and
	// recorded in the session marker).
	Partition string `protobuf:"bytes,6,opt,name=partition,proto3" json:"partition,omitempty"`
}

func (x *EnsureSessionRequest) Reset() {
	*x = EnsureSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_remoteagent_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsureSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureSessionRequest) ProtoMessage() {}

func (x *EnsureSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureSessionRequest.ProtoReflect.Descriptor instead.
func (*EnsureSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureSessionRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *EnsureSessionRequest) GetClaimUid() string {
	if x != nil {
		return x.ClaimUid
	}
	return ""
}

func (x *EnsureSessionRequest) GetClaimNamespace() string {
	if x != nil {
		return x.ClaimNamespace
	}
	return ""
}

func (x *EnsureSessionRequest) GetClaimName() string {
	if x != nil {
		return x.ClaimName
	}
	return ""
}

func (x *EnsureSessionRequest) GetRequests() []string {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *EnsureSessionRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

type EnsureSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready             bool   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	CudaDriverVersion string `protobuf:"bytes,2,opt,name=cuda_driver_version,json=cudaDriverVersion,proto3" json:"cuda_driver_version,omitempty"`
	Message           string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// server_endpoint is the lupine-server address clients must be given
	// (URL form), as the agent currently knows it. Empty when the agent has
	// no routable address for its server yet.
	ServerEndpoint string `protobuf:"bytes,4,opt,name=server_endpoint,json=serverEndpoint,proto3" json:"server_endpoint,omitempty"`
}

func (x *EnsureSessionResponse) Reset() {
	*x = EnsureSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_remoteagent_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsureSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureSessionResponse) ProtoMessage() {}

func (x *EnsureSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureSessionResponse.ProtoReflect.Descriptor instead.
func (*EnsureSessionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureSessionResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *EnsureSessionResponse) GetCudaDriverVersion() string {
	if x != nil {
		return x.CudaDriverVersion
	}
	return ""
}

func (x *EnsureSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnsureSessionResponse) GetServerEndpoint() string {
	if x != nil {
		return x.ServerEndpoint
	}
	return ""
}

type ServerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerInfoRequest) Reset() {
	*x = ServerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_remoteagent_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoRequest) ProtoMessage() {}

func (x *ServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{2}
}

type ServerInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listening bool `protobuf:"varint,1,opt,name=listening,proto3" json:"listening,omitempty"`
	// endpoint is the lupine-server address other nodes should use (URL
	// form): advertised by the operator, or discovered by the agent. Empty
	// while unknown.
	Endpoint          string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CudaDriverVersion string `protobuf:"bytes,3,opt,name=cuda_driver_version,json=cudaDriverVersion,proto3" json:"cuda_driver_version,omitempty"`
	NodeName          string `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// agent_endpoint is this agent's own address other nodes should use for
	// EnsureSession (grpc://host:port). Empty while unknown, or when the
	// agent listens on a unix socket only.
	AgentEndpoint string `protobuf:"bytes,5,opt,name=agent_endpoint,json=agentEndpoint,proto3" json:"agent_endpoint,omitempty"`
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_remoteagent_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_remoteagent_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_remoteagent_api_proto_rawDescGZIP(), []int{3}
}

func (x *ServerInfoResponse) GetListening() bool {
	if x != nil {
		return x.Listening
	}
	return false
}

func (x *ServerInfoResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ServerInfoResponse) GetCudaDriverVersion() string {
	if x != nil {
		return x.CudaDriverVersion
	}
	return ""
}

func (x *ServerInfoResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ServerInfoResponse) GetAgentEndpoint() string {
	if x != nil {
		return x.AgentEndpoint
	}
	return ""
}

var File_pkg_api_remoteagent_api_proto protoreflect.FileDescriptor

var file_pkg_api_remoteagent_api_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0xcf, 0x01, 0x0a,
	0x14, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x0f,
	0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x69, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa0,
	0x01, 0x0a, 0x15, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x2e,
	0x0a, 0x13, 0x63, 0x75, 0x64, 0x61, 0x5f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x75, 0x64,
	0x61, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc2, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x75, 0x64, 0x61, 0x5f,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x75, 0x64, 0x61, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0xb8, 0x01, 0x0a, 0x0b,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x58, 0x0a, 0x0d, 0x45,
	0x6e, 0x73, 0x75, 0x72, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x73, 0x75, 0x72,
	0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6e,
	0x73, 0x75, 0x72, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_remoteagent_api_proto_rawDescOnce sync.Once
	file_pkg_api_remoteagent_api_proto_rawDescData = file_pkg_api_remoteagent_api_proto_rawDesc
)

func file_pkg_api_remoteagent_api_proto_rawDescGZIP() []byte {
	file_pkg_api_remoteagent_api_proto_rawDescOnce.Do(func() {
		file_pkg_api_remoteagent_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_remoteagent_api_proto_rawDescData)
	})
	return file_pkg_api_remoteagent_api_proto_rawDescData
}

var file_pkg_api_remoteagent_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_remoteagent_api_proto_goTypes = []interface{}{
	(*EnsureSessionRequest)(nil),  // 0: remoteagent.EnsureSessionRequest
	(*EnsureSessionResponse)(nil), // 1: remoteagent.EnsureSessionResponse
	(*ServerInfoRequest)(nil),     // 2: remoteagent.ServerInfoRequest
	(*ServerInfoResponse)(nil),    // 3: remoteagent.ServerInfoResponse
}
var file_pkg_api_remoteagent_api_proto_depIdxs = []int32{
	0, // 0: remoteagent.RemoteAgent.EnsureSession:input_type -> remoteagent.EnsureSessionRequest
	2, // 1: remoteagent.RemoteAgent.ServerInfo:input_type -> remoteagent.ServerInfoRequest
	1, // 2: remoteagent.RemoteAgent.EnsureSession:output_type -> remoteagent.EnsureSessionResponse
	3, // 3: remoteagent.RemoteAgent.ServerInfo:output_type -> remoteagent.ServerInfoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_remoteagent_api_proto_init() }
func file_pkg_api_remoteagent_api_proto_init() {
	if File_pkg_api_remoteagent_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_remoteagent_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnsureSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_remoteagent_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnsureSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_remoteagent_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_remoteagent_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_remoteagent_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_remoteagent_api_proto_goTypes,
		DependencyIndexes: file_pkg_api_remoteagent_api_proto_depIdxs,
		MessageInfos:      file_pkg_api_remoteagent_api_proto_msgTypes,
	}.Build()
	File_pkg_api_remoteagent_api_proto = out.File
	file_pkg_api_remoteagent_api_proto_rawDesc = nil
	file_pkg_api_remoteagent_api_proto_goTypes = nil
	file_pkg_api_remoteagent_api_proto_depIdxs = nil
}
