// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: pkg/api/remoteagent/api.proto

package remoteagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteAgent_EnsureSession_FullMethodName = "/remoteagent.RemoteAgent/EnsureSession"
	RemoteAgent_ServerInfo_FullMethodName    = "/remoteagent.RemoteAgent/ServerInfo"
)

// RemoteAgentClient is the client API for RemoteAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RemoteAgent is served by the GPU-node agent that runs alongside
// lupine-server (design v2.0 D24). It is called cross-node by the consumer
// side kubelet-plugin (--mode=inject) inside NodePrepareResources (D2/D20).
type RemoteAgentClient interface {
	// EnsureSession materializes the session quota directory for a claim
	// allocation on this node (idempotent) and reports readiness.
	EnsureSession(ctx context.Context, in *EnsureSessionRequest, opts ...grpc.CallOption) (*EnsureSessionResponse, error)
	// ServerInfo reports whether lupine-server is accepting connections and
	// the node's CUDA ceiling.
	ServerInfo(ctx context.Context, in *ServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error)
}

type remoteAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteAgentClient(cc grpc.ClientConnInterface) RemoteAgentClient {
	return &remoteAgentClient{cc}
}

func (c *remoteAgentClient) EnsureSession(ctx context.Context, in *EnsureSessionRequest, opts ...grpc.CallOption) (*EnsureSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureSessionResponse)
	err := c.cc.Invoke(ctx, RemoteAgent_EnsureSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteAgentClient) ServerInfo(ctx context.Context, in *ServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerInfoResponse)
	err := c.cc.Invoke(ctx, RemoteAgent_ServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteAgentServer is the server API for RemoteAgent service.
// All implementations must embed UnimplementedRemoteAgentServer
// for forward compatibility.
//
// RemoteAgent is served by the GPU-node agent that runs alongside
// lupine-server (design v2.0 D24). It is called cross-node by the consumer
// side kubelet-plugin (--mode=inject) inside NodePrepareResources (D2/D20).
type RemoteAgentServer interface {
	// EnsureSession materializes the session quota directory for a claim
	// allocation on this node (idempotent) and reports readiness.
	EnsureSession(context.Context, *EnsureSessionRequest) (*EnsureSessionResponse, error)
	// ServerInfo reports whether lupine-server is accepting connections and
	// the node's CUDA ceiling.
	ServerInfo(context.Context, *ServerInfoRequest) (*ServerInfoResponse, error)
	mustEmbedUnimplementedRemoteAgentServer()
}

// UnimplementedRemoteAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteAgentServer struct{}

func (UnimplementedRemoteAgentServer) EnsureSession(context.Context, *EnsureSessionRequest) (*EnsureSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureSession not implemented")
}
func (UnimplementedRemoteAgentServer) ServerInfo(context.Context, *ServerInfoRequest) (*ServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerInfo not implemented")
}
func (UnimplementedRemoteAgentServer) mustEmbedUnimplementedRemoteAgentServer() {}
func (UnimplementedRemoteAgentServer) testEmbeddedByValue()                     {}

// UnsafeRemoteAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteAgentServer will
// result in compilation errors.
type UnsafeRemoteAgentServer interface {
	mustEmbedUnimplementedRemoteAgentServer()
}

func RegisterRemoteAgentServer(s grpc.ServiceRegistrar, srv RemoteAgentServer) {
	// If the following call panics, it indicates UnimplementedRemoteAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteAgent_ServiceDesc, srv)
}

func _RemoteAgent_EnsureSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteAgentServer).EnsureSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteAgent_EnsureSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteAgentServer).EnsureSession(ctx, req.(*EnsureSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteAgent_ServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteAgentServer).ServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteAgent_ServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteAgentServer).ServerInfo(ctx, req.(*ServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteAgent_ServiceDesc is the grpc.ServiceDesc for RemoteAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remoteagent.RemoteAgent",
	HandlerType: (*RemoteAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureSession",
			Handler:    _RemoteAgent_EnsureSession_Handler,
		},
		{
			MethodName: "ServerInfo",
			Handler:    _RemoteAgent_ServerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/remoteagent/api.proto",
}
