// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: pkg/api/registry/api.proto

package registry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VDeviceRegistry_RegisterContainerDevice_FullMethodName = "/registry.VDeviceRegistry/RegisterContainerDevice"
)

// VDeviceRegistryClient is the client API for VDeviceRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VDeviceRegistryClient interface {
	RegisterContainerDevice(ctx context.Context, in *ContainerDeviceRequest, opts ...grpc.CallOption) (*ContainerDeviceResponse, error)
}

type vDeviceRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewVDeviceRegistryClient(cc grpc.ClientConnInterface) VDeviceRegistryClient {
	return &vDeviceRegistryClient{cc}
}

func (c *vDeviceRegistryClient) RegisterContainerDevice(ctx context.Context, in *ContainerDeviceRequest, opts ...grpc.CallOption) (*ContainerDeviceResponse, error) {
	out := new(ContainerDeviceResponse)
	err := c.cc.Invoke(ctx, VDeviceRegistry_RegisterContainerDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VDeviceRegistryServer is the server API for VDeviceRegistry service.
// All implementations must embed UnimplementedVDeviceRegistryServer
// for forward compatibility
type VDeviceRegistryServer interface {
	RegisterContainerDevice(context.Context, *ContainerDeviceRequest) (*ContainerDeviceResponse, error)
	mustEmbedUnimplementedVDeviceRegistryServer()
}

// UnimplementedVDeviceRegistryServer must be embedded to have forward compatible implementations.
type UnimplementedVDeviceRegistryServer struct {
}

func (UnimplementedVDeviceRegistryServer) RegisterContainerDevice(context.Context, *ContainerDeviceRequest) (*ContainerDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterContainerDevice not implemented")
}
func (UnimplementedVDeviceRegistryServer) mustEmbedUnimplementedVDeviceRegistryServer() {}

// UnsafeVDeviceRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VDeviceRegistryServer will
// result in compilation errors.
type UnsafeVDeviceRegistryServer interface {
	mustEmbedUnimplementedVDeviceRegistryServer()
}

func RegisterVDeviceRegistryServer(s grpc.ServiceRegistrar, srv VDeviceRegistryServer) {
	s.RegisterService(&VDeviceRegistry_ServiceDesc, srv)
}

func _VDeviceRegistry_RegisterContainerDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VDeviceRegistryServer).RegisterContainerDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VDeviceRegistry_RegisterContainerDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VDeviceRegistryServer).RegisterContainerDevice(ctx, req.(*ContainerDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VDeviceRegistry_ServiceDesc is the grpc.ServiceDesc for VDeviceRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VDeviceRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registry.VDeviceRegistry",
	HandlerType: (*VDeviceRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterContainerDevice",
			Handler:    _VDeviceRegistry_RegisterContainerDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/registry/api.proto",
}
