{{- if and .Values.scheduler.enabled .Values.scheduler.schedulerExtender.tls.enabled -}}
{{- if .Values.scheduler.schedulerExtender.tls.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "vgpu-manager.scheduler" . }}-issuer
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager.scheduler" . }}
    {{- include "vgpu-manager.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}