{{- if .Values.devicePlugin.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vgpu-manager.device-plugin" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager.device-plugin" . }}
    {{- include "vgpu-manager.labels" . | nindent 4 }}
data:
  {{- if .Values.devicePlugin.nodeConfig.yaml }}
  nodeConfig.yaml: |
    {{- .Values.devicePlugin.nodeConfig.yaml | nindent 4 }}
  {{- else }}
  nodeConfig.json: |
    {{- .Values.devicePlugin.nodeConfig.json | nindent 4 }}
  {{- end }}
{{- end }}