{{- if .Values.devicePlugin.enabled -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vgpu-manager.device-plugin" . }}-as-role
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager.device-plugin" . }}
    {{- include "vgpu-manager.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vgpu-manager.device-plugin" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "vgpu-manager.device-plugin" . }}:role
  apiGroup: rbac.authorization.k8s.io
{{- end }}