{{- if .Values.scheduler.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vgpu-manager.scheduler" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager.scheduler" . }}
    {{- include "vgpu-manager.labels" . | nindent 4 }}
data:
  {{- if ge (.Values.scheduler.kubeScheduler.imageTag | substr 3 5 | atoi) 22 }}
  config.yaml: |
    {{- if gt (.Values.scheduler.kubeScheduler.imageTag | substr 3 5 | atoi) 25 }}
    apiVersion: kubescheduler.config.k8s.io/v1
    {{- else }}
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    {{- end }}
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: {{ .Values.scheduler.schedulerName }}
      resourceNamespace: {{ .Release.Namespace | quote }}
    profiles:
    - schedulerName: {{ .Values.scheduler.schedulerName }}
    extenders:
    - urlPrefix: "http://127.0.0.1:{{ .Values.scheduler.schedulerExtender.commands.serverBindPort }}/scheduler"
      filterVerb: filter
      bindVerb: bind
      enableHTTPS: false
      nodeCacheCapable: true
      weight: 1
      httpTimeout: 30s
      managedResources:
      - name: "nvidia.com/vgpu-number"
        ignoredByScheduler: true
      - name: "nvidia.com/vgpu-core"
        ignoredByScheduler: true
      - name: "nvidia.com/vgpu-memory"
        ignoredByScheduler: true
  {{- else }}
  config.json: |
    {
      "kind": "Policy",
      "apiVersion": "v1",
      "extenders": [
        {
          "urlPrefix": "http://127.0.0.1:{{ .Values.scheduler.schedulerExtender.commands.serverBindPort }}/scheduler",
          "filterVerb": "filter",
          "bindVerb": "bind",
          "enableHttps": false,
          "weight": 1,
          "nodeCacheCapable": true,
          "httpTimeout": 30000000000,
          "managedResources": [
            {
              "name": "nvidia.com/vgpu-number",
              "ignoredByScheduler": true
            },
            {
              "name": "nvidia.com/vgpu-core",
              "ignoredByScheduler": true
            },
            {
              "name": "nvidia.com/vgpu-memory",
              "ignoredByScheduler": true
            }
          ],
          "ignoreable": false
        }
      ]
    }
  {{- end }}
{{- end }}