{{- if .Values.kubeletPlugin.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vgpu-manager-dra-driver.kubelet-plugin" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager-dra-driver.kubelet-plugin" . }}
    {{- include "vgpu-manager-dra-driver.labels" . | nindent 4 }}
{{- end }}
