{{- $monitor := .Values.kubeletPlugin.containers.monitor | default dict }}
{{- $metricsPort := .Values.kubeletPlugin.containers.plugin.commands.metricsPort | default 0 }}
{{- $pluginMetrics := and (gt ($metricsPort | int) 0) .Values.kubeletPlugin.serviceMonitor.enabled }}
{{- if and .Values.kubeletPlugin.enabled (or $pluginMetrics $monitor.enabled) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") -}}
{{- $sm := .Values.kubeletPlugin.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vgpu-manager-dra-driver.kubelet-plugin" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager-dra-driver.kubelet-plugin" . }}
    {{- include "vgpu-manager-dra-driver.labels" . | nindent 4 }}
    {{- with $sm.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    {{- if $pluginMetrics }}
    - path: /metrics
      port: metrics
      {{- with $sm.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with $sm.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with $sm.relabelings }}
      relabelings: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $sm.metricRelabelings }}
      metricRelabelings: {{ toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if $monitor.enabled }}
    - path: /metrics
      port: device-metrics
      scheme: http
      {{- with $sm.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with $sm.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with $sm.relabelings }}
      relabelings: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $sm.metricRelabelings }}
      metricRelabelings: {{ toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "vgpu-manager-dra-driver.kubelet-plugin" . }}
      {{- include "vgpu-manager-dra-driver.selectorLabels" . | nindent 6 }}
{{- end }}
