# Default values for vgpu-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""
# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# Set up the image repository for vgpu-manager
image: coldzerofear/vgpu-manager
# Overrides the image tag whose default is the chart appVersion.
imageTag: ""
imagePullPolicy: IfNotPresent

# Deployment configuration of the scheduler section
scheduler:
  # Should the scheduler be deployed? (default: true)
  enable: true
  # pod labels
  labels: {}
  # pod annotations
  annotations: {}
  # Number of deployed replicas (default: 1)
  replicas: 1
  # Name of deployed scheduler (default : vgpu-scheduler)
  schedulerName: "vgpu-scheduler"
  nodeSelector: {}
  tolerations: []
  terminationGracePeriodSeconds: 30
  kubeScheduler:
    image: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler
    imageTag: "v1.28.15"
    imagePullPolicy: IfNotPresent
    commands:
      featureGates: ""
      logLevel: 3
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  schedulerExtender:
    commands:
      kubeApiQps: 20.0
      kubeApiBurst: 30
      # scheduler-extender service port (default: 3456)
      serverBindPort: 3456
      # The pprof service port used for debugging: (default disable: 0)
      pprofBindPort: 0
      # Supported feature gates:
      # - SerialBindNode
      # - GPUTopology
      featureGates: ""
      logLevel: 3
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

# Deployment configuration of the deviceplugin section
devicePlugin:
  # Should the deviceplugin be deployed? (default: true)
  enable: true
  # pod labels
  labels: {}
  # pod annotations
  annotations:
    # This annotation is deprecated. Kept here for backward compatibility
    # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
    scheduler.alpha.kubernetes.io/critical-pod: ""
  # Container deployment using host network mode (default: false)
  hostNetwork: false
  # Grace period for container recycling (default: 30s)
  terminationGracePeriodSeconds: 30
  # Node labels to be deployed
  nodeSelector:
    vgpu-manager-enable: enable
  tolerations:
    # This toleration is deprecated. Kept here for backward compatibility
    # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
  # Define container security context
  securityContext:
    # If the container encounters the following errors, try using privileged mode
    # Failed to initialize NVML: Unknown Error
    # privileged: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
      add: ["SYS_ADMIN"]
  runtimeClassName: ""
  # The root directory configured in the start command of kubelet (default: /var/lib/kubelet)
  kubeletRootDir: "/var/lib/kubelet"
  # Configure the host path used by vgpu manager (default: /etc/vgpu-manager)
  vgpuManagerDir: "/etc/vgpu-manager"
  # Cgroup driver, generally does not require manual configuration (Supported values: systemd | cgroupfs)
  cgroupDriver: ""
  devicePlugin:
    commands:
      kubeApiQps: 20.0
      kubeApiBurst: 30
      # The number for NVIDIA device split. (default: 10)
      deviceSplitCount: 10
      # The ratio for NVIDIA device cores scaling. (default: 1.0)
      deviceCoresScaling: 1.0
      # The ratio for NVIDIA device memory scaling. (default: 1.0)
      deviceMemoryScaling: 1.0
      # The default gpu memory block size is 1MB. (default: 1)
      deviceMemoryFactor: 1
      # The pprof service port used for debugging: (default disable: 0)
      pprofBindPort: 0
      gdsEnabled: false
      mofedEnabled: false
      # Supported feature gates:
      # - CorePlugin
      # - MemoryPlugin
      # - Reschedule
      # - GPUTopology
      featureGates: ""
      logLevel: 3
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
  deviceMonitor:
    commands:
      kubeApiQps: 20.0
      kubeApiBurst: 30
      # Monitoring service port (default: 3456)
      serverBindPort: 3456
      # The pprof service port used for debugging: (default disable: 0)
      pprofBindPort: 0
      logLevel: 3
    resources:
      requests:
        cpu: 20m
        memory: 128Mi

  # Define node differentiation configuration files for device plugins
  nodeConfig:
    json: | 
      [
        {
          "nodeName": "example",
          "cgroupDriver": "systemd",
          "deviceSplitCount": 5,
          "deviceMemoryScaling": 1,
          "deviceMemoryFactor": 1,
          "deviceCoresScaling": 1,
          "excludeDevices": "4-7",
          "gdsEnabled": false,
          "mofedEnabled": false
        }
      ]

# Installing the Webhook service requires installing the Cert-Manager component in advance to provide a self signed certificate for the service.
webhook:
  # Should the webhook be deployed? (default: false)
  enable: false
  # Certificate validity period. (default: one year)
  certDuration: 8760h
  # The last refresh time of the certificate. (default: 360h)
  certRenewBefore: 360h
  # mutate webhook failure Policy (Supported values: Ignore | Fail)
  failurePolicy: Ignore
  # pod labels
  labels: {}
  # pod annotations
  annotations: {}
  # Number of deployed replicas (default: 1)
  replicas: 1
  # Grace period for container recycling (default: 10s)
  terminationGracePeriodSeconds: 10
  # Node labels to be deployed
  nodeSelector: {}
  tolerations: []
  # Webhook will not be effective for resources under these namespaces.
  excludeNamespaces:
    - kube-system
    - cert-manager
  commands:
    # webhook service port (default: 9443)
    serverBindPort: 9443
    # The pprof service port used for debugging: (default disable: 0)
    pprofBindPort: 0
    # CertDir is the directory that contains the server key and certificate.
    certDir: /tmp/k8s-webhook-server/serving-certs
    # Default node scheduling policy. (supported values: binpack | spread)
    defaultNodePolicy: binpack
    # Default device scheduling policy. (supported values: binpack | spread)
    defaultDevicePolicy: binpack
    # Default device list topology mode. (supported values: numa | link)
    defaultTopologyMode: ""
    logLevel: 4
  # Webhook container requests resources
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
