{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vgpu-manager.webhook" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager.webhook" . }}
    {{- include "vgpu-manager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.webhook.commands.serverBindPort }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/component: {{ include "vgpu-manager.webhook" . }}
    {{- include "vgpu-manager.selectorLabels" . | nindent 4 }}
{{- end }}