{{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "vgpu-manager-dra-driver.webhook" . }}-cert
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager-dra-driver.webhook" . }}
    {{- include "vgpu-manager-dra-driver.labels" . | nindent 4 }}
  name: {{ include "vgpu-manager-dra-driver.webhook" . }}-mutate
{{ include "vgpu-manager-dra-driver.mutatingWebhooks" (dict "ctx" . "caBundle" "") }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "vgpu-manager-dra-driver.webhook" . }}-cert
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager-dra-driver.webhook" . }}
    {{- include "vgpu-manager-dra-driver.labels" . | nindent 4 }}
  name: {{ include "vgpu-manager-dra-driver.webhook" . }}-validate
{{ include "vgpu-manager-dra-driver.validatingWebhooks" (dict "ctx" . "caBundle" "") }}
{{- end }}
